In [24]:
#lagd av Knut D. Selstad

import csv
import numpy as np
import random

In [25]:
directions = [
    (-1, 0), (1, 0),  # Left and Right
    (0, -1), (0, 1),  # Up and Down
    (-1, 1), (1, -1)  # Upper-left and Lower-right for staggered rows
]

In [26]:

def generate_empty_board(board_size):
    return np.zeros((board_size, board_size), dtype=int)
    

In [27]:
def generate_list_of_empy_cells(board_size):
    return [(i, j) for i in range(board_size) for j in range(board_size)]

In [28]:
def check_winner(board, position):
    player = board[position]
    board_size = board.shape[0]
    
    # Initialize search
    stack = [position]
    visited = set()
    
    # Track if the player touches the required sides
    touches_left = touches_right = touches_top = touches_bottom = False
    
    while stack:
        current = stack.pop()
        if current in visited:
            continue
        visited.add(current)
        
        x, y = current
        
        # Check if the current position touches the required sides
        if player == -1:
            if y == 0:
                touches_left = True
            if y == board_size - 1:
                touches_right = True
        elif player == 1:
            if x == 0:
                touches_top = True
            if x == board_size - 1:
                touches_bottom = True
        
        # If both sides are touched, the player wins
        if (player == -1 and touches_left and touches_right) or (player == 1 and touches_top and touches_bottom):
            return True
        
        # Explore neighbors
        for dx, dy in directions:
            nx, ny = x + dx, y + dy
            if 0 <= nx < board_size and 0 <= ny < board_size and board[nx, ny] == player:
                stack.append((nx, ny))
    
    return False
    

In [19]:
board_size = 5
board = generate_empty_board(board_size=board_size)
list_empty_cells = generate_list_of_empy_cells(board_size=board_size)


In [20]:
for i in range(board_size*board_size):
    random_cell = random.choice(list_empty_cells)
    list_empty_cells.remove(random_cell)
    board[random_cell] = 1 if i % 2 == 1 else -1
    if check_winner(board, random_cell):
        print(f"Player {1 if i % 2 == 1 else -1} wins!")
        print(board)
        break

Player -1 wins!
[[ 0  1  0 -1  1]
 [-1  1  1  1 -1]
 [-1 -1 -1 -1  1]
 [ 1  1  1  1 -1]
 [ 1 -1 -1 -1 -1]]


In [21]:
def save_board_to_csv(board, winner, filename='game_results_9x9_random_ja.csv'):
    # Flatten the board and append the winner
    flattened_board = board.flatten().tolist()
    flattened_board.append(winner)
    
    # Write to CSV file
    with open(filename, mode='a', newline='') as file:
        writer = csv.writer(file)
        writer.writerow(flattened_board)

In [22]:
for j in range(400000):
    board_size = 9
    board = generate_empty_board(board_size=board_size)
    list_empty_cells = generate_list_of_empy_cells(board_size=board_size)
    player = random.choice([1,-1])
    start_player = player
    for i in range(board_size * board_size):
        random_cell = random.choice(list_empty_cells)
        list_empty_cells.remove(random_cell)
        board[random_cell] = player
        if check_winner(board, random_cell):
            winner = player
            if winner == start_player:
                break
            else:
                save_board_to_csv(board, winner)
                break
          
        player *= -1